/*
 * Serialization API
 * All endpoints related to the serialization assignment.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sdk.serialization.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import sdk.serialization.model.PCBuildRequest;

/**
 * OrderRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-05-10T17:06:50.964221+02:00[Europe/Amsterdam]")
public class OrderRequest {
  @JsonProperty("customerId")
  private String customerId;

  @JsonProperty("pcBuildRequests")
  private List<PCBuildRequest> pcBuildRequests = new ArrayList<>();

  public OrderRequest customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public OrderRequest pcBuildRequests(List<PCBuildRequest> pcBuildRequests) {
    this.pcBuildRequests = pcBuildRequests;
    return this;
  }

  public OrderRequest addPcBuildRequestsItem(PCBuildRequest pcBuildRequestsItem) {
    this.pcBuildRequests.add(pcBuildRequestsItem);
    return this;
  }

   /**
   * Get pcBuildRequests
   * @return pcBuildRequests
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PCBuildRequest> getPcBuildRequests() {
    return pcBuildRequests;
  }

  public void setPcBuildRequests(List<PCBuildRequest> pcBuildRequests) {
    this.pcBuildRequests = pcBuildRequests;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRequest orderRequest = (OrderRequest) o;
    return Objects.equals(this.customerId, orderRequest.customerId) &&
        Objects.equals(this.pcBuildRequests, orderRequest.pcBuildRequests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, pcBuildRequests);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRequest {\n");
    
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    pcBuildRequests: ").append(toIndentedString(pcBuildRequests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

