/*
 * Serialization API
 * All endpoints related to the serialization assignment.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sdk.serialization.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import sdk.serialization.model.CPU;
import sdk.serialization.model.GPU;
import sdk.serialization.model.PCCase;
import sdk.serialization.model.PSU;

/**
 * PC
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-05-21T13:46:39.597167+02:00[Europe/Amsterdam]")
public class PC {
  @JsonProperty("pcCase")
  private PCCase pcCase = null;

  @JsonProperty("cpu")
  private CPU cpu = null;

  @JsonProperty("gpu")
  private GPU gpu = null;

  @JsonProperty("psu")
  private PSU psu = null;

  public PC pcCase(PCCase pcCase) {
    this.pcCase = pcCase;
    return this;
  }

   /**
   * Get pcCase
   * @return pcCase
  **/
  @ApiModelProperty(required = true, value = "")
  public PCCase getPcCase() {
    return pcCase;
  }

  public void setPcCase(PCCase pcCase) {
    this.pcCase = pcCase;
  }

  public PC cpu(CPU cpu) {
    this.cpu = cpu;
    return this;
  }

   /**
   * Get cpu
   * @return cpu
  **/
  @ApiModelProperty(required = true, value = "")
  public CPU getCpu() {
    return cpu;
  }

  public void setCpu(CPU cpu) {
    this.cpu = cpu;
  }

  public PC gpu(GPU gpu) {
    this.gpu = gpu;
    return this;
  }

   /**
   * Get gpu
   * @return gpu
  **/
  @ApiModelProperty(required = true, value = "")
  public GPU getGpu() {
    return gpu;
  }

  public void setGpu(GPU gpu) {
    this.gpu = gpu;
  }

  public PC psu(PSU psu) {
    this.psu = psu;
    return this;
  }

   /**
   * Get psu
   * @return psu
  **/
  @ApiModelProperty(required = true, value = "")
  public PSU getPsu() {
    return psu;
  }

  public void setPsu(PSU psu) {
    this.psu = psu;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PC PC = (PC) o;
    return Objects.equals(this.pcCase, PC.pcCase) &&
        Objects.equals(this.cpu, PC.cpu) &&
        Objects.equals(this.gpu, PC.gpu) &&
        Objects.equals(this.psu, PC.psu);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pcCase, cpu, gpu, psu);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PC {\n");
    
    sb.append("    pcCase: ").append(toIndentedString(pcCase)).append("\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    gpu: ").append(toIndentedString(gpu)).append("\n");
    sb.append("    psu: ").append(toIndentedString(psu)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

